/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Aluno
 */
public class TelaInicial extends javax.swing.JFrame {

    @Override
    public void setExtendedState(int i) {
        
    }
private void redimensionarTela() {

    Toolkit kit = Toolkit.getDefaultToolkit();
    Dimension tamTela = kit.getScreenSize();
    //Pegando a largura total da tela
    int larg = tamTela.width;
    //Pegando a altura total da tela
    int alt = tamTela.height;
    /*Se você quiser que o seu JFrame ocupe 70% da tela por exemplo 
    multiplique a largura e altura totais por 0,7*/

    //Mandando o JFrame utilizar suas dimensões
    this.setSize(alt, larg);
}
    
    public TelaInicial() {
        redimensionarTela();
        initComponents();
        super.setExtendedState(MAXIMIZED_BOTH);
        this.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btn_cadastro = new javax.swing.JButton();
        btn_analisar = new javax.swing.JButton();
        btn_trato = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        btn_trato1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 0));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Logo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 0, 770, 310);

        btn_cadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cadastro.setText("Cadastrar Animais");
        btn_cadastro.setToolTipText("Cadastrar novos animais");
        btn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastro);
        btn_cadastro.setBounds(480, 500, 290, 70);

        btn_analisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_analisar.setText("Analisar/Atualizar Dados");
        btn_analisar.setToolTipText("Analisar, pesquisar ou alterar dados");
        btn_analisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analisarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_analisar);
        btn_analisar.setBounds(480, 380, 290, 70);

        btn_trato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_trato.setText("Custos ");
        btn_trato.setToolTipText("Exibir tabela de trato");
        btn_trato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tratoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_trato);
        btn_trato.setBounds(860, 500, 300, 70);

        btn_sair.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.setToolTipText("Fechar software");
        btn_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sairMouseClicked(evt);
            }
        });
        getContentPane().add(btn_sair);
        btn_sair.setBounds(480, 600, 670, 70);

        btn_trato1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_trato1.setText("Classificação dos Animais");
        btn_trato1.setToolTipText("Exibir tabela de trato");
        btn_trato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trato1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_trato1);
        btn_trato1.setBounds(860, 380, 290, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/informacoes.png"))); // NOI18N
        jLabel2.setToolTipText("Tutorial de uso ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 100, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/desenvolvi.png"))); // NOI18N
        jLabel3.setToolTipText("Desenvolvedores");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1460, 810, 70, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/vaca.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 1750, 940);

        setSize(new java.awt.Dimension(1574, 946));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sairMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sairMouseClicked

    private void btn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroActionPerformed
        TelaCadastro tela = new TelaCadastro();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cadastroActionPerformed

    private void btn_analisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analisarActionPerformed
        TelaAnalise tela = new TelaAnalise();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_analisarActionPerformed

    private void btn_tratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tratoActionPerformed
        TelaFinanceiro tela = new TelaFinanceiro();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_tratoActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        TelaTutorial tela = new TelaTutorial();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        TelaDesenvolvedores tela = new TelaDesenvolvedores();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_trato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trato1ActionPerformed
        TelaClasse tela = new TelaClasse();
        tela.setVisible(true);
         
        dispose();
    }//GEN-LAST:event_btn_trato1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_analisar;
    private javax.swing.JButton btn_cadastro;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_trato;
    private javax.swing.JButton btn_trato1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
